name: Build

on:
  workflow_call:
    inputs:
      is_develop:
        required: true
        type: boolean
      is_master:
        required: true
        type: boolean
      can_deploy_on_dev:
        required: true
        type: boolean
      can_deploy_on_production:
        required: true
        type: boolean

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Debug variables
        run: |
          echo "can_deploy_on_dev=${{ inputs.can_deploy_on_dev }}"
          echo "can_deploy_on_production=${{ inputs.can_deploy_on_production }}"
