name: Deploy

on:
  workflow_call:
    inputs:
      app-url:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: ./deploy
      - name: Extract files
        run: unzip './deploy/*.zip' -d './deploy'
      - name: Create config.js file
        run: |
          echo "const env = (() => ({
          appUrl: ${{ inputs.app-url }}
          }))();" > ./deploy/dist/apps/smart-room/config.js
      - name: show config.js
        run:  cat ./deploy/dist/apps/smart-room/config.js
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ vars.AZURE_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./deploy/dist/apps/smart-room" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

