name: Deploy

on:
  workflow_call:
    inputs:
      app-url:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: ./deploy
      - name: Extract files
        run: unzip './deploy/*.zip' -d './deploy'
      - name: Create config.js file
        run: |
          echo "const env = (() => ({
          appUrl: {{ inputs.app-url }},
          }))();" > ./deploy/config.js
      - name: files in deploy
        run: ls -la ./deploy


      - name: Deploy Application
        run: |
          echo "Application URL: ${{ inputs.app-url }}"

